### ISSUE TITLE
Improve vignettes

### ISSUE THREAD

**Issue by fvitalini** [miraisolutions/SmaRP#101]
The rendering of Rmd files does not seem consistent with regards to figures positioning. Suggestion is to refrain from using sentences such as "plot below", as the image might be above the text. An example of this is in the `smarp-server.Rmd`, Plot 1, but it is not necessarily restricted to that.

In the current setup, the vignettes that use images do refer to the images with names such as `Plot1` but the images do not have any caption. An example of this is in the `smarp-server.Rmd`, but it is not necessarily restricted to that. The suggestion is to add captions to all figures.

Another suggestion is to add the Mirai logo to the vignettes. This would give Mirai more visibility.

**Comment by riccardoporreca** [comment]
See more general concerns about maintenance of vignettes and their current status in #122
