### ISSUE TITLE
Review and align pension funds naming

### ISSUE THREAD

**Issue by riccardoporreca** [miraisolutions/SmaRP#103]
We refer to the (various components of) the retirement pension fund in different ways across the app inputs, plots, table, report.

This should be aligned for consistency and for readability (especially within the report). One example of such problem is within the report where we describe the plots as

>The graphs above display the amounts at the end of each year for the Pillar I, Pillar II and Tax Benefit fund

without any connection between this and the labels of the plot (besides the fact the they should be Pillar II and Pillar III => dedicated bugfix #105).

Another inconsistency example is using in the report table captions Arabic numerals instead of Roman for the full pillar names (Pillar 2/3 intead of Pillar II/III).

What we definitely miss in general is a better connection between Occupational / Private and corresponding Pillars.

Table with new agreed names 

| Full name | Full Pillar | Short Pillar | Plot Label | Table  |
| --- | --- | --- | --- | --- |
| Occupational Fund - Second Pillar | 2nd/second Pillar | P2 | 2nd Pillar| P2 |
| Private Fund - Third Pillar | 3rd/third Pillar | P3 | 3rd Pillar | P3 |
| Tax Benefits | - | - | Tax Benefits | Tax |

**Comment by gabrielfoix** [comment]
I think we should follow the naming convention from wikipedia.  It's the first reference in the report.
https://en.wikipedia.org/wiki/Pension_system_in_Switzerland

**Comment by riccardoporreca** [comment]
@gabrielfoix, @nfarabullini, is the merged #127 addressing all points in the description and aligning all names to the table above?

It looks like nothing was done there for the Plot Labels and the related missing connection between the plots in the report and the text describing them. Is it also still OK to use P2 and P3 as short names?

**Comment by riccardoporreca** [comment]
@nfarabullini, I think we can still use this issue instead of spinning off a new issue (#128), given that the table in the description has been updated. We will just have another PR (and possibly a branch) addeessing the missing parts of this issue in addition to the already merged PR #127.
