### ISSUE TITLE
Disclaimer moves when panels in sidebar are opened

### ISSUE THREAD

**Issue by fvitalini** [miraisolutions/SmaRP#117]
The disclaimer is in a separate row than the main and the side panel. This means that, when the panels in the sidebar are opened, the disclaimer moves, despite being floated to the right. 

Suggestion:

- either make the disclaimer part of the main panel.
- or align disclaimer to the left with the sidebar panels

**Comment by riccardoporreca** [comment]
@fvitalini, I guess according to #34 this was intentional, meaning we probably wanted it to be at the very bottom just above the footer, not just below the download button (the precise placement was then refined in #67).

**Comment by gabrielfoix** [comment]
Yes, although might look ugly, this was intentional. The idea is that the disclaimer is not too important and can be pushed to the bottom always.
In case we have better ideas, we open a new issue.
