### ISSUE TITLE
Additional nomenclature edits

### ISSUE THREAD

**Issue by nfarabullini** [miraisolutions/SmaRP#128]
- In legend: Occupational Fund has to be changed to 2nd Pillar, Private Fund -> 3rd Pillar
- In equations: Pillar3 has to become P3

reference issue #103

**Comment by riccardoporreca** [comment]
@nfarabullini, I would suggest to close this in view of https://github.com/miraisolutions/SmaRP/issues/103#issuecomment-496563260

**Comment by riccardoporreca** [comment]
Also closing the corresponding placeholder branch [feature/128-nomenclature-adj](../tree/feature/128-nomenclature-adj)
